using System.Text.RegularExpressions;
using Domain.Exceptions;

namespace Domain.ValueObjects;

/// <summary>
/// An email address. Guaranteed valid + normalized (trimmed, lowercased)
/// once constructed. As a record, value equality, GetHashCode, ==, != and
/// ToString are generated by the compiler — no base class needed.
/// </summary>
public sealed record Email
{
    private static readonly Regex Pattern = new(
        @"^[^@\s]+@[^@\s]+\.[^@\s]+$",
        RegexOptions.Compiled);

    public string Value { get; }

    // Private: the only way in is Create(), so an invalid Email can't exist.
    private Email(string value) => Value = value;

    public static Email Create(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
        {
            throw new ValidationException("Email is required.");
        }

        var normalized = input.Trim().ToLowerInvariant();

        if (!Pattern.IsMatch(normalized))
        {
            throw new ValidationException($"'{input}' is not a valid email address.");
        }

        return new Email(normalized);
    }

    public override string ToString() => Value;
}
